# Generated by Django 3.2.9 on 2022-04-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=168, verbose_name='Имя клиента')),
                ('mail', models.CharField(max_length=168, verbose_name='Почта клиента')),
                ('phone', models.CharField(max_length=168, verbose_name='Телефон клиента')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
