# Generated by Django 3.2.9 on 2021-12-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioFunctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=168, verbose_name='Название объекта')),
                ('preview', models.TextField(max_length=250, verbose_name='Предпросмотр')),
                ('text', models.TextField(verbose_name='Текст по объекту')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Актуальность объекта')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('start_date', models.DateTimeField(verbose_name='Начало работы по объекту')),
                ('finish_date', models.DateTimeField(verbose_name='Конец работы по объекту')),
                ('object_status', models.TextField(default='В работе', max_length=20, verbose_name='Предпросмотр')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
