# Generated by Django 3.2.9 on 2021-12-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioimage',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Актуальность фото'),
        ),
    ]
