# Generated by Django 3.2.9 on 2021-12-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_auto_20211220_0056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioFunction',
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='function_condition',
            field=models.BooleanField(default=False, verbose_name='Функционал: Кондиционирование'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='function_light',
            field=models.BooleanField(default=True, verbose_name='Функционал: Освещение'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='function_remote',
            field=models.BooleanField(default=False, verbose_name='Функционал: Удаленное управление'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='function_security',
            field=models.BooleanField(default=False, verbose_name='Функционал: Безопасность'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='function_shutters',
            field=models.BooleanField(default=False, verbose_name='Функционал: Шторы'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='function_ventilation',
            field=models.BooleanField(default=False, verbose_name='Функционал: Вентиляция'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='function_voice_control',
            field=models.BooleanField(default=False, verbose_name='Функционал: Голосовые помощники'),
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='function_warm_floors',
            field=models.BooleanField(default=False, verbose_name='Функционал: Теплые полы'),
        ),
    ]
