# Generated by Django 3.2.9 on 2021-12-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0005_auto_20211221_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioobject',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='portfolioobject',
            name='start_date',
        ),
    ]
