# Generated by Django 3.2.9 on 2021-12-21 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_auto_20211221_0140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioimage',
            name='is_main_photo',
        ),
        migrations.AddField(
            model_name='portfolioobject',
            name='main_photo',
            field=models.FileField(null=True, upload_to='object_photos/', verbose_name='Главное фото'),
        ),
    ]
