# Generated by Django 3.2.9 on 2021-12-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0007_auto_20211222_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioobject',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='object_photos/', verbose_name='Главное фото'),
        ),
    ]
