# Generated by Django 3.2.9 on 2022-01-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=168, verbose_name='Название статьи')),
                ('main_image', models.ImageField(blank=True, upload_to='article_photos/', verbose_name='Изображение для статьи')),
                ('preview', models.TextField(max_length=250, verbose_name='Предпросмотр')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Актуальность статьи')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
                'ordering': ['-add_datetime'],
            },
        ),
    ]
